# Generated by Django 6.0.5 on 2026-06-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('child_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('school_name', models.CharField(max_length=100)),
                ('school_type', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('school_code', models.CharField(blank=True, max_length=50, null=True)),
                ('year_created', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('director_name', models.CharField(max_length=100)),
                ('director_email', models.EmailField(max_length=254)),
                ('director_phone', models.CharField(max_length=20)),
                ('director_password', models.CharField(max_length=255)),
            ],
        ),

    ]
