# Generated by Django 6.0.5 on 2026-06-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('email', models.EmailField(default='test@example.com', max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(choices=[('RABAT', 'Rabat'), ('CASABLANCA', 'Casablanca'), ('FES', 'Fès'), ('MARRAKECH', 'Marrakech'), ('TANGER', 'Tanger'), ('AGADIR', 'Agadir'), ('MEKNES', 'Meknès'), ('OUJDA', 'Oujda'), ('KENITRA', 'Kénitra'), ('TETOUAN', 'Tétouan')], default='RABAT', max_length=50)),
                ('country', models.CharField(default='Morocco', max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('school_name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('dropped', 'Dropped')], default='active', max_length=20)),
                ('enrollment_date', models.DateField()),
                ('parent_name_father', models.CharField(max_length=100)),
                ('parent_phone_father', models.CharField(max_length=20)),
                ('parent_email_father', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_job_father', models.CharField(blank=True, max_length=100)),
                ('parent_name_mother', models.CharField(max_length=100)),
                ('parent_phone_mother', models.CharField(max_length=20)),
                ('parent_email_mother', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_job_mother', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
