# Generated by Django 6.0.5 on 2026-06-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_place_of_birth_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
