# Generated by Django 6.0.5 on 2026-06-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='director_password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='school',
            name='director_email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='director_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='director_phone',
        ),
    ]
