# Generated by Django 6.0.5 on 2026-06-23 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_director_password_school_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='accounts.school')),
            ],
        ),
    ]
