# Generated by Django 6.0.5 on 2026-06-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staff_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('SECRETARY', 'Secrétaire'), ('Comptable', 'Comptable'), ('SUPERVISOR', 'Surveillant'), ('ADMIN', 'Administrateur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(choices=[('Morocco', 'Morocco'), ('France', 'France'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('Belgium', 'Belgium'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('United States', 'United States'), ('Algeria', 'Algeria'), ('Tunisia', 'Tunisia'), ('Mauritania', 'Mauritania')], default='Morocco', max_length=100),
        ),
    ]
