# Generated by Django 6.0.5 on 2026-07-02 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_staff_role_alter_student_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school_name',
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.school'),
            preserve_default=False,
        ),
    ]
